import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oleh Kozina Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
